server:
  port: 8888
services:
  user: ${USER_SERVICE}
app:
  api-prefix: /api
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: "http://${services.user}/"
          predicates:
            - Path=${app.api-prefix}/user/**
          filters:
            - StripPrefix=1

        - id: school-service
          uri: http://${SCHOOL_SERVICE}/
          predicates:
            - Path=${app.api-prefix}/school/**
          filters:
            - StripPrefix=1

        - id: subject-service
          uri: http://${SUBJECT_SERVICE}/
          predicates:
            - Path=${app.api-prefix}/subject/**
          filters:
            - StripPrefix=1

        - id: resource-service
          uri: http://${RESOURCE_SERVICE}/
          predicates:
            - Path=${app.api-prefix}/resource/**
          filters:
            - StripPrefix=1

springdoc:
  api-docs:
    path: '/v3/api-docs'
    enabled: true
  swagger-ui:
    operationsSorter: method
    try-it-out-enabled: true
    path: '/swagger-ui.html'
    urls:
      - url: /api/user/v3/api-docs
        name: user-service
      - url: /api/subject/swagger/v1/swagger.json
        name: subject-service
      - url: /api/school/v3/api-docs
        name: school-service
      - url: /api/resource/v3/api-docs
        name: resource-service
    enabled: true